import { Inter } from "next/font/google";  // import font do google 
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });  //inicializa a fonte importada com subconjunto [latin] caracteres latinos

export const metadata = {                 // meta dados mesmo função de meta do HTML (titulo, descrição, ajuda a mecanismos de busca)
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {  // define components de layout das paginas ligadas a este layout.js
  return (
    <html lang="pt-br">
      <body className={inter.className}>
       <div>Menu top</div>
       <div>Menu Lateral</div>
        {children}
        </body>
    </html>
  );
}
